### ISSUE TITLE
Syntax error in shell script

### ISSUE THREAD

**Issue by jeffbrl** [zenvdeluca/network-wrapper#1]
I realize you tested on Ubuntu 12.04; however, I wouldn't think using 14.04 would cause a shell script syntax problem unless an error condition is exercising untested lines to handle failure cases.

root@docker-do:~/network-wrapper# ./network-wrapper br0 $(docker run --net none -d nginx) dhcp
./network-wrapper: 34: ./network-wrapper: Syntax error: "(" unexpected (expecting ";;")
root@docker-do:~/network-wrapper# uname -a
Linux docker-do 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@docker-do:~/network-wrapper# docker -v
Docker version 1.0.1, build 990021a
root@docker-do:~/network-wrapper#

**Comment by zenvdeluca** [comment]
:+1: @jeffbrl
