### ISSUE TITLE
dhclient 4.2.4 does not support -H flag

### ISSUE THREAD

**Issue by jeffbrl** [zenvdeluca/network-wrapper#4]
The dhclient package version in Ubuntu 12.04 and 14.04 is 4.2.4.

root@ubuntu:~# ip netns exec 13642 dhclient -pf "/var/run/dhclient-docker.pid" -H a4bb329aea72 eth0
Internet Systems Consortium DHCP Client 4.2.4
Copyright 2004-2012 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Usage: dhclient [-4|-6] [-SNTP1dvrx] [-nw] [-p <port>] [-D LL|LLT]
                [-s server-addr] [-cf config-file] [-lf lease-file]
                [-pf pid-file] [--no-pid] [-e VAR=val]
                [-sf script-file] [interface]
root@ubuntu:~#

[root@centos ~]# dhclient -h
Internet Systems Consortium DHCP Client 4.2.5
Copyright 2004-2013 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Usage: dhclient [-4|-6] [-SNTP1dvrx] [-nw] [-p <port>] [-D LL|LLT]
                [-s server-addr] [-cf config-file] [-lf lease-file]
                [-pf pid-file] [--no-pid] [-e VAR=val]
                [-I <dhcp-client-identifier>] [-B]
                [-H <host-name> | -F <fqdn.fqdn>] [-timeout <timeout>]
                [-V <vendor-class-identifier>]
                [-R <request option list>]
                [-sf script-file] [interface]

This version of ISC DHCP is based on the release available
on ftp.isc.org.  Features have been added and other changes
have been made to the base software release in order to make
it work better with this distribution.

Please report for this software via the CentOS Bugs Database:
    http://bugs.centos.org/

**Comment by zenvdeluca** [comment]
For Ubuntu I'm currently expecting you to use udhcpc, which supports the hostname flag.

**Comment by jeffbrl** [comment]
OK. The text in your blog is - "Tested on Ubuntu 12.04 (udhcpc) and CentOS 7 (dhclient)". To me this sounds like a description of the test environment rather than a requirement of udhcpc for Ubuntu.

**Comment by kbron** [comment]
i´m having the -H error, current version of dhclient is 4.3.5 and there's no -H option

ystems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Unknown command: -h
Usage: dhclient [-4|-6] [-SNTPRI1dvrxi] [-nw] [-p <port>] [-D LL|LLT] 
                [-s server-addr] [-cf config-file]
                [-df duid-file] [-lf lease-file]
                [-pf pid-file] [--no-pid] [-e VAR=val]
                [-sf script-file] [interface]*

I tried to run sepecifying udhcpc in the cmd line, but the response was: "works with dhclient only"

runing on kali linux

sudo network-wrapper br0 $(docker run --rm --name xuleta  --net none -dit alpinao:1.0 /bin/sh) udhcpc 62:02:39:fb:12:e3
GUESTNAME: 6dab15866b8f4610f746d58fe5908f1529476d9f53591149a61adb57f8e6f334
IPADDR: udhcpc
MACADDR: 62:02:39:fb:12:e3
only DHCP client supported at the moment
